name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.8.4
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Cache cabal packages
      - name: Cache cabal packages
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('*.cabal') }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      # Build the project
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      # Run tests
      - name: Run tests
        run: cabal test all

      # Check for missing cabal or project files
      - name: Validate cabal files
        run: |
          if [ ! -f *.cabal ]; then
            echo "Error: Missing .cabal file. Please add one to your repository.";
            exit 1;
          fi
          if [ ! -f cabal.project ]; then
            echo "Warning: Missing cabal.project file. Consider adding one for non-trivial projects.";
          fi
